//
//  SearchProductsViewController.swift
//  examen
//
//  Created BE-006 on 29/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchProductsViewController: UIViewController, SearchProductsViewProtocol {
    @IBOutlet weak var searchTextField: UITextField!
    @IBOutlet weak var tagsCollectionView: TagCollectionView!
    @IBOutlet weak var productsCollectionView: ProductsCollectionView!
    
    var presenter: SearchProductsPresenterProtocol?
    
    //Variables
    var tags:[String] = ["sony","Nintendo","Computer","sony","Nintendo","Computer","sony","Nintendo","Computer"]
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        tagsCollectionView.register(UINib(nibName: "TagCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "TagCell")
        tagsCollectionView.setValues(tags: tags)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    @IBAction func searchButtonAction(_ sender: Any) {
    }
    
}
