//
//  SearchProductsPresenter.swift
//  examen
//
//  Created BE-006 on 29/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchProductsPresenter: SearchProductsPresenterProtocol {
    
    weak private var view: SearchProductsViewProtocol?
    var interactor: SearchProductsInteractorProtocol?
    private let router: SearchProductsWireframeProtocol

    init(interface: SearchProductsViewProtocol, interactor: SearchProductsInteractorProtocol?, router: SearchProductsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getTags() -> [String] {
        if let tags = interactor?.getTags(){
            return tags
        }
        return []
    }
    
    func saveTags(tags: [String]) {
        interactor?.saveTags(tags: tags)
    }
    
    func searchProduct(text: String, page: Int) {
        interactor?.searchProduct(text: text, page: page)
    }
    
    func returnInfo(product:Products){
        view?.returnInfo(product: product)
    }
    
    func returnError(){
        view?.returnError()
    }
}
