//
//  SearchProductsInteractor.swift
//  examen
//
//  Created BE-006 on 29/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchProductsInteractor: SearchProductsInteractorProtocol {

    weak var presenter: SearchProductsPresenterProtocol?
}
