//
//  SearchProductsProtocols.swift
//  examen
//
//  Created BE-006 on 29/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchProductsWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchProductsPresenterProtocol: class {

}

//MARK: Interactor -
protocol SearchProductsInteractorProtocol: class {

  var presenter: SearchProductsPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchProductsViewProtocol: class {

  var presenter: SearchProductsPresenterProtocol?  { get set }
}

//MARK: RemoteData -

protocol SearchProductsRemoteDataManagerProtocol {
    
}
